### ISSUE TITLE
成就系统无法触发

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#1]
游戏版本：V1.3（V0.9.24）
系统版本：Windows 10 专业版 2004
问题：在通关简单模式后，无法触发对应的成就，退出后Steam上也没有显示相关的成就；
其他情况：其他成就有部分能成功激活。

**Comment by SakuraNeko** [comment]
BUG Fix On V0.9.5β.

**Comment by SuraNight** [comment]
Copy that.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 落樱<mailto:notifications@github.com>
发送时间: 2020年6月18日 14:56
收件人: MoespiritStudios/BossAss<mailto:BossAss@noreply.github.com>
抄送: Sura<mailto:surainnight@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [MoespiritStudios/BossAss] 成就系统无法触发 (#1)


BUG Fix On V0.9.5β.

―
