### ISSUE TITLE
设置页面中“开局剧情”勾选框的说明文字修改

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#11]
**新增建议：** 修改设置中的剧情跳过的文本及功能
**游戏版本：** 0.9.14β
**系统版本：** 任意操作系统版本(版本无关)
**建议：**

- 将设置菜单中的“开局剧情”的文本改成“隐藏开局剧情”，并反转选项参数使功能与文本说明对应；

**Comment by SakuraNeko** [comment]
Enhancement finish.
