### ISSUE TITLE
在剧情界面添加跳过按钮

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#12]
**新增建议：** 在部分剧情界面添加跳过按钮
**游戏版本：** 0.9.14β
**系统版本：** 任意操作系统版本(版本无关)
**新增需求：** 

1. 在所有剧情部分的显示部分界面的左上角添加**跳过**按钮，玩家点击该按钮后可以跳过该段剧情；
2. 当玩家在剧情界面选择跳过剧情时，弹出含有文字 **是否跳过当前剧情？** 的提示弹窗供玩家确认。
玩家单击左侧确认按钮后跳过当前剧情，单击右侧取消按键则恢复原状。

**Comment by SakuraNeko** [comment]
Enhancement finish.
