### ISSUE TITLE
游戏设置内制作群按钮相关的功能未被实现

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#13]
**游戏版本：** 0.9.14β
**系统版本：** 任意操作系统版本(版本无关)·
**存在问题：** 设置菜单中的制作群相关功能未被完整实现。
**问题详情：**

- 按需求，只有当玩家通关任意一次游戏（不限难度和分数）后，才能在点击该按钮时展示制作群界面；
- 如玩家未达到需求（任意一次通关）时点击按钮，制作群界面不应该被打开，且游戏直接播放选择错误的音效；

**Comment by SakuraNeko** [comment]
Enhancement finish.
