### ISSUE TITLE
更新成就系统内容

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#14]
**新增建议：** 更新成就系统内容
**游戏版本：** 0.9.14β
**系统版本：** 任意操作系统版本(版本无关)
**详细信息：** 

1. 策划新增了一个成就 **百卡斩**， 其解锁条件是 **玩家在任意一局游戏中达成一百次连击** ；
2. 我们调换了新增成就（百卡斩）和白金成就的位置：原来的白金成就ID变成了 23， 新增成就的ID为 22；
3. 需要程序重新处理相关SDK接口，修改和这两个成就触发有关的模块。

**Comment by SakuraNeko** [comment]
Enhancement finish.
