### ISSUE TITLE
为主界面增加存档覆盖的防呆设计

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#15]
**新增建议：** 新增读档提示
**游戏版本：** 0.9.14β
**系统版本：** 任意操作系统版本(版本无关)
**功能建议：** 

1. 当玩家在主界面点击新游戏时，如果检测到玩家游戏存档，则弹出含有文字 **“您已有的存档将被覆盖（不可恢复），请确认”** 的提示弹窗供玩家确认；
玩家单击左侧 **确认** 按钮后将开始新游戏，单击右侧 **取消** 按钮则恢复原状。

**Comment by SakuraNeko** [comment]
Enhancement finish.
