### ISSUE TITLE
新增跳过剧情提示

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#16]
新增建议：新增跳过剧情提示
游戏版本：0.9.14β
系统版本：任意操作系统版本(版本无关)
建议：当玩家在剧情界面选择跳过剧情时，弹出 **即将跳过剧情是否继续** 的提示弹窗。

**Comment by SakuraNeko** [comment]
该需求已经被合并到  **在剧情界面添加跳过按钮** #12 。
