### ISSUE TITLE
除16:9外的分辨率比例内容缺失

### ISSUE THREAD

**Issue by SuraNight** [MoespiritStudios/BossAss#3]
【内测用户反馈】
游戏对以下屏幕比例支持存在异常。
4：3
5：4
3：2
16：10
21：9

**Comment by SakuraNeko** [comment]
@SuraNight 需要与BUG相关的更多截图，另外可以将设置菜单返回关闭按钮移位的情况写入本issue，合并处理。

**Comment by SakuraNeko** [comment]
Bug Fix on Ver:0.9.7β-20200628
