### ISSUE TITLE
游戏分数与成就解锁对应发生错误

### ISSUE THREAD

**Issue by 997731588** [MoespiritStudios/BossAss#6]
游戏版本：0.9.7β
系统版本：任意操作系统版本(版本无关)
问题现象：当游戏结束时候30-60分的打分与0-30分的玩家解锁成就相同，无法解锁30-60分获得的“正式员工”成就
如何复现： 结束时候打分30-60的玩家无“正式员工成就”
备注：当玩家通关一局游戏时，其分数和解锁成就之间对应发生问题。为防止设计错误，当玩家到达某个分数时候解锁该成就和其以下分数成就（如一个玩家到达多少分解锁部门主管后同时解锁该分数以下的社畜和实习生成就）
（展示bug视频已上传）

**Comment by SakuraNeko** [comment]
BUG FIXED.
