### ISSUE TITLE
游戏无法进入第二第三阶段，且没有出现转场剧情

### ISSUE THREAD

**Issue by 997731588** [MoespiritStudios/BossAss#8]
游戏版本：0.9.13β
系统版本：任意操作系统版本(版本无关)·
问题现象：游戏无法进入第二第三阶段，且没有出现转场剧情，右下角Ui界面上的”√“号也未显示
游戏中右下方进度条到满为止没有出现转场剧情且没有出现第二第三难度卡片，
如何复现：正常游玩即可复现，录屏发在了qq群里（可能是在游戏时候更改分辨率有关，调回原分辨率并未解决问题）
（展示bug视频已上传）

**Comment by SakuraNeko** [comment]
@997731588 已经在0.9.14上提供修正代码，该版本已经完成推送，请辅助检查。

**Comment by SakuraNeko** [comment]
问题已经验收，确认修复。
