### ISSUE TITLE
设置中可加入：跳过开局剧情按键

### ISSUE THREAD

**Issue by 997731588** [MoespiritStudios/BossAss#9]
新增建议：在游戏内剧情界面加入跳过按钮
游戏版本：0.9.13β
系统版本：任意操作系统版本(版本无关)
建议：在玩家多次死亡后，一再被播放的剧情变得无聊，增加一个跳过按钮方便玩家跳过剧情。

**Comment by SakuraNeko** [comment]
对需求进行变更。

**Comment by SakuraNeko** [comment]
其内容已经被合并到 **在剧情界面添加跳过按钮** #12。
